from __future__ import annotations

import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .protocol import task_step_text
from .task_id import split_task_ref
from .task_store import TaskStore


INDEX_JSONL = "task_index.jsonl"
INDEX_MARKDOWN = "TASK_INDEX.md"

_OPENAI_KEY_RE = re.compile(r"(?<![A-Za-z0-9])sk-[A-Za-z0-9_-]{12,}", re.IGNORECASE)
_PASSWORD_ASSIGNMENT_RE = re.compile(
    r"[A-Za-z0-9_.-]*(?:password|passwd|pwd)(?:_hash)?\s*[:=]\s*"
    r"(?:\"[^\"]*\"|'[^']*'|[^\s,;]+)",
    re.IGNORECASE,
)
_WHITESPACE_RE = re.compile(r"\s+")


def refresh_task_index(board_root: str | Path) -> list[dict[str, Any]]:
    """Rewrite the global task lookup index from authoritative task state."""
    root = Path(board_root).expanduser().resolve()
    store = TaskStore(root)
    entries = [_index_entry(task) for task in store.list_tasks()]
    entries.sort(key=lambda item: (str(item.get("updated_at") or ""), str(item.get("task_id") or "")), reverse=True)
    _atomic_write_text(
        root / INDEX_JSONL,
        "".join(json.dumps(entry, ensure_ascii=False, sort_keys=True) + "\n" for entry in entries),
    )
    _atomic_write_text(root / INDEX_MARKDOWN, _render_markdown(entries))
    return entries


def _index_entry(task: dict[str, Any]) -> dict[str, Any]:
    task_id = str(task.get("id") or "")
    workspace = task.get("workspace") if isinstance(task.get("workspace"), dict) else {}
    extensions = task.get("extensions") if isinstance(task.get("extensions"), dict) else {}
    final_callback = extensions.get("agentbc.final_callback") if isinstance(extensions.get("agentbc.final_callback"), dict) else {}
    lineage = extensions.get("agentbc.lineage") if isinstance(extensions.get("agentbc.lineage"), dict) else {}
    errors = task.get("errors") if isinstance(task.get("errors"), list) else []
    latest_error = errors[-1] if errors and isinstance(errors[-1], dict) else {}
    try:
        parsed_code, parsed_iteration = split_task_ref(task_id)
    except ValueError:
        parsed_code, parsed_iteration = task_id, ""
    report_value = str(workspace.get("report_file") or "")
    return {
        "task_id": task_id,
        "task_code": _compact(workspace.get("task_code") or lineage.get("task_code") or parsed_code, 32),
        "iteration": _compact(workspace.get("iteration") or parsed_iteration or lineage.get("iteration_index") or "", 8),
        "title": _compact(task.get("title"), 96),
        "description": _compact(_description(task), 160),
        "status": _compact(task.get("status"), 32),
        "result": _compact(
            final_callback.get("summary") or latest_error.get("message") or task.get("status") or "",
            180,
        ),
        "assignee": _compact(task.get("assignee"), 32),
        "created_at": _compact(task.get("created_at"), 40),
        "updated_at": _compact(task.get("updated_at"), 40),
        "report_file": _compact(report_value, 240),
    }


def _description(task: dict[str, Any]) -> str:
    steps = task.get("steps")
    if isinstance(steps, list):
        for step in steps:
            text = task_step_text(step)
            if text:
                return text
    return str(task.get("title") or "")


def _render_markdown(entries: list[dict[str, Any]]) -> str:
    lines = [
        "# AgentBC Task Index",
        "",
        "> Generated by AgentBC Runner/TaskService. Do not edit manually.",
        "",
        "| Updated | Task | Iter | Status | Executor | Title | Result | Report |",
        "|---|---|---|---|---|---|---|---|",
    ]
    if not entries:
        lines.append("| - | - | - | - | - | - | - | - |")
    for entry in entries:
        report_file = entry.get("report_file") or ""
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(entry.get("updated_at")),
                    f"`{_md(entry.get('task_code') or entry.get('task_id'))}`",
                    f"`{_md(entry.get('iteration'))}`",
                    f"`{_md(entry.get('status'))}`",
                    f"`{_md(entry.get('assignee'))}`",
                    _md(entry.get("title")),
                    _md(entry.get("result")),
                    f"`{_md(report_file)}`",
                ]
            )
            + " |"
        )
    lines.append("")
    lines.append(f"Machine-readable index: `{INDEX_JSONL}`")
    lines.append("")
    return "\n".join(lines)


def _compact(value: Any, limit: int) -> str:
    text = _redact(str(value or ""))
    text = _WHITESPACE_RE.sub(" ", text).strip()
    if len(text) <= limit:
        return text
    return text[: max(limit - 3, 0)].rstrip() + "..."


def _md(value: Any) -> str:
    return _compact(value, 180).replace("|", "\\|")


def _redact(value: str) -> str:
    value = _OPENAI_KEY_RE.sub("[REDACTED]", value)
    return _PASSWORD_ASSIGNMENT_RE.sub("[REDACTED]", value)


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)
